# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  - id: deb
    package_name: rtmp2hls
    homepage: https://github.com/Thor77/rtmp2hls
    maintainer: Thor77 <thor77 at thor77 dot org>
    description: Simple rtmp server with hls output
    license: MIT
    formats:
      - deb
    bindir: /usr/bin
    contents:
      - src: doc/rtmp2hls.service
        dst: /lib/systemd/system/rtmp2hls.service
      - src: config.toml
        dst: /etc/rtmp2hls.toml
        type: config
    scripts:
      postinstall: 'doc/postinstall.sh'
dockers:
  - image_templates:
      - ghcr.io/thor77/rtmp2hls:latest
      - ghcr.io/thor77/rtmp2hls:{{ .Tag }}

